/* Al-Ameen member quiz experience. Demo questions can be replaced by admin-managed data. */
(() => {
  const root = () => document.getElementById('quizRoot');
  const userKey = 'ayfaQuizMember';
  const resultKey = 'ayfaQuizResults';
  const previewMode = window.QUIZ_PREVIEW_MODE === true;
  const apiUrl = String(window.QUIZ_SCRIPT_URL || '').trim();
  const api = async payload => { if(!apiUrl)throw new Error('Quiz data connection is not set up yet.');const response=await fetch(apiUrl,{method:'POST',mode:'cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok||data.success===false||data.error)throw new Error(data.error||'ದತ್ತಾಂಶ ಸೇವೆಯನ್ನು ಸಂಪರ್ಕಿಸಲಾಗಲಿಲ್ಲ.');return data; };
  const savedAuth=()=>{try{return JSON.parse(sessionStorage.getItem(userKey)||'null')}catch(_){return null}};
  let member = null, questions = [], index = 0, selected = [], typed = '', seconds = 30, ticker = null, startedAt = 0, points = 0, questionLocked = false, interruptionNotice = false, submittedAnswers=[];
  const demoQuestions = [
    ...[
      ['ಕರ್ನಾಟಕದ ರಾಜಧಾನಿ ಯಾವುದು?', ['ಬೆಂಗಳೂರು','ಮೈಸೂರು','ಮಂಗಳೂರು','ಹುಬ್ಬಳ್ಳಿ'], ['ಬೆಂಗಳೂರು']],
      ['ಭಾರತದ ರಾಷ್ಟ್ರಧ್ವಜದಲ್ಲಿ ಎಷ್ಟು ಬಣ್ಣಗಳಿವೆ?', ['ಎರಡು','ಮೂರು','ನಾಲ್ಕು','ಐದು'], ['ಮೂರು']],
      ['ಭಾರತದ ರಾಷ್ಟ್ರಗೀತೆ ಯಾವುದು?', ['ವಂದೇ ಮಾತರಂ','ಜನ ಗಣ ಮನ','ಸಾರೆ ಜಹಾಂ ಸೆ ಅಚ್ಚಾ','ನಮ್ಮ ನಾಡು'], ['ಜನ ಗಣ ಮನ']],
      ['ನೀರಿನ ರಾಸಾಯನಿಕ ಸೂತ್ರ ಯಾವುದು?', ['CO₂','O₂','H₂O','NaCl'], ['H₂O']],
      ['ವಾರದಲ್ಲಿ ಎಷ್ಟು ದಿನಗಳಿವೆ?', ['ಐದು','ಆರು','ಏಳು','ಎಂಟು'], ['ಏಳು']],
      ['ಸೂರ್ಯ ಯಾವ ದಿಕ್ಕಿನಲ್ಲಿ ಉದಯಿಸುತ್ತಾನೆ?', ['ಪಶ್ಚಿಮ','ಉತ್ತರ','ದಕ್ಷಿಣ','ಪೂರ್ವ'], ['ಪೂರ್ವ']],
      ['ಭಾರತದ ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಣಿ ಯಾವುದು?', ['ಸಿಂಹ','ಹುಲಿ','ಆನೆ','ನವಿಲು'], ['ಹುಲಿ']],
      ['ಒಂದು ವರ್ಷದಲ್ಲಿ ಎಷ್ಟು ತಿಂಗಳು?', ['10','11','12','13'], ['12']],
      ['ಭೂಮಿಗೆ ಬೆಳಕು ನೀಡುವ ನಕ್ಷತ್ರ ಯಾವುದು?', ['ಚಂದ್ರ','ಸೂರ್ಯ','ಧ್ರುವತಾರೆ','ಶುಕ್ರ'], ['ಸೂರ್ಯ']],
      ['ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಹಣ್ಣುಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ', ['ಮಾವು','ಕ್ಯಾರೆಟ್','ಬಾಳೆಹಣ್ಣು','ಆಲೂಗಡ್ಡೆ'], ['ಮಾವು','ಬಾಳೆಹಣ್ಣು']]
    ].map(([text, options, answers]) => ({type:'multiple',text,options,answers,time:30})),
    ...[
      ['ಕರ್ನಾಟಕದ ರಾಜ್ಯ ಪ್ರಾಣಿ ಯಾವುದು?','ಆನೆ'],['ಕೆಂಪು ಗ್ರಹ ಎಂದು ಯಾವುದನ್ನು ಕರೆಯುತ್ತಾರೆ?','ಮಂಗಳ'],['ಭಾರತದ ಸ್ವಾತಂತ್ರ್ಯ ದಿನ ಯಾವಾಗ?','ಆಗಸ್ಟ್ 15'],['ಜೇನುತುಪ್ಪವನ್ನು ತಯಾರಿಸುವ ಕೀಟ ಯಾವುದು?','ಜೇನುನೊಣ'],['ಭಾರತದ ರಾಷ್ಟ್ರೀಯ ಹೂವು ಯಾವುದು?','ಕಮಲ'],['ಭೂಮಿಯ ಏಕೈಕ ನೈಸರ್ಗಿಕ ಉಪಗ್ರಹ ಯಾವುದು?','ಚಂದ್ರ']
    ].map(([text, answer]) => ({type:'typing',text,answers:[answer],time:35})),
    {type:'person',text:'ಈ ವ್ಯಕ್ತಿಯನ್ನು ಗುರುತಿಸಿ',media:'fa-user-tie',answers:['ಮಹಾತ್ಮ ಗಾಂಧಿ','ಗಾಂಧಿ'],time:30},
    {type:'person',text:'ಈ ವ್ಯಕ್ತಿಯನ್ನು ಗುರುತಿಸಿ',media:'fa-user',answers:['ಸ್ವಾಮಿ ವಿವೇಕಾನಂದ','ವಿವೇಕಾನಂದ'],time:30},
    {type:'sound',text:'ಈ ಧ್ವನಿಯನ್ನು ಗುರುತಿಸಿ',media:'fa-volume-high',answers:['ಗಂಟೆ','ಬೆಲ್','bell'],time:30},
    {type:'dance',text:'ಈ ನೃತ್ಯ ಶೈಲಿಯನ್ನು ಗುರುತಿಸಿ',media:'fa-film',answers:['ಭರತನಾಟ್ಯ','bharatanatyam'],time:35}
  ];
  const typeNames = {multiple:'ಬಹು ಆಯ್ಕೆ',typing:'ಟೈಪ್ ಮಾಡಿ',person:'ವ್ಯಕ್ತಿಯನ್ನು ಗುರುತಿಸಿ',sound:'ಧ್ವನಿಯನ್ನು ಗುರುತಿಸಿ',dance:'ನೃತ್ಯವನ್ನು ಗುರುತಿಸಿ'};
  const safe = value => String(value || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function renderMedia(q){if(q.mediaURL){const url=safe(q.mediaURL);if(q.type==='sound')return `<audio controls class="quiz-media-player" src="${url}">Audio</audio>`;if(q.type==='dance')return `<video controls playsinline class="quiz-media-video" src="${url}">Video</video>`;return `<img class="quiz-media-image" src="${url}" alt="ಪ್ರಶ್ನೆಯ ಚಿತ್ರ">`;}return q.media?`<div class="quiz-media-placeholder"><i class="fa-solid ${safe(q.media)}"></i></div><p class="quiz-note">Demo preview: ಮಾಧ್ಯಮವನ್ನು Admin ಸೇರಿಸಿದಾಗ ಇಲ್ಲಿ ತೋರಿಸಲಾಗುತ್ತದೆ.</p>`:'';}
  function view(id){ const app=document.getElementById('appContainer'); if(app)app.setAttribute('data-active-view',id==='quizView'?'quiz':'dashboard'); document.querySelectorAll('.view-section').forEach(el=>el.classList.add('hidden')); document.querySelectorAll('.dashboard-only').forEach(el=>el.classList.add('hidden')); document.getElementById(id)?.classList.remove('hidden'); if(id==='dashboardView')document.getElementById('dashboardHomeActions')?.classList.remove('hidden'); window.scrollTo({top:0,behavior:'smooth'}); }
  window.openQuiz = function(){ view('quizView'); member=previewMode?JSON.parse(localStorage.getItem(userKey)||'null'):savedAuth()?.member||null; if(!previewMode&&!member){showMemberAuth('login');return;} renderHome(); };
  window.showDashboard = window.showDashboard || function(){ view('dashboardView'); };
  function renderHome(){
    const past=previewMode?JSON.parse(localStorage.getItem(resultKey)||'[]'):[], last=past[0];
    root().innerHTML=`<div class="quiz-card"><div class="quiz-eyebrow"><i class="fa-solid fa-sparkles"></i> AL-AMEEN YOUTH FEDERATION</div><h1 class="quiz-title">ಜ್ಞಾನ ಪರೀಕ್ಷಿಸಿ,<br>ಅಂಕ ಗಳಿಸಿ!</h1><p class="quiz-subtitle">ಸಣ್ಣ, ಆಸಕ್ತಿದಾಯಕ ಪ್ರಶ್ನೆಗಳು — ನಿಮ್ಮ ಜ್ಞಾನಕ್ಕೆ ಒಂದು ಮೋಜಿನ ಸವಾಲು.</p><div class="quiz-hero"><i class="fa-solid fa-trophy"></i><div><strong>ಸಾಪ್ತಾಹಿಕ ಕ್ವಿಜ್</strong><small>ಎಲ್ಲರಿಗೂ ಮುಕ್ತ • 20 ಪ್ರಶ್ನೆಗಳು</small></div></div><div class="quiz-stats"><div class="quiz-stat"><b>20</b><span>ಪ್ರಶ್ನೆಗಳು</span></div><div class="quiz-stat"><b>~12</b><span>ನಿಮಿಷ</span></div><div class="quiz-stat"><b>${last?last.score+'/20':'—'}</b><span>ಕೊನೆಯ ಅಂಕ</span></div></div>${member?`<p class="quiz-note">ನಮಸ್ಕಾರ, <b>${safe(member.name)}</b>! ${last?`ನಿಮ್ಮ ಹಿಂದಿನ ಅಂಕ <b>${last.score}/20</b>.`:''}</p><button class="quiz-button" onclick="beginQuiz()">ಕ್ವಿಝ್ ಪ್ರಾರಂಭಿಸಿ <i class="fa-solid fa-arrow-right"></i></button><button class="quiz-button secondary" style="margin-top:10px" onclick="showQuizProfile()">ನನ್ನ ಪ್ರೊಫೈಲ್ ಮತ್ತು ಅಂಕಪಟ್ಟಿ</button>`:`<button class="quiz-button" onclick="beginQuiz()">ಕ್ವಿಝ್ ಪ್ರಾರಂಭಿಸಿ</button>`}<div class="quiz-safe"><i class="fa-solid fa-circle-info"></i><span>ಹಿಂದೆ ಹೋದರೆ, ChatGPT/ಬೇರೆ app ತೆರೆಯಿದರೆ ಅಥವಾ ಕರೆ ಬಂದರೆ quiz ಪರದೆ ತಾತ್ಕಾಲಿಕವಾಗಿ ಹಿನ್ನೆಲೆಗೆ ಹೋಗಬಹುದು. ಪ್ರಶ್ನೆಯ timer ಮುಂದುವರಿಯುತ್ತದೆ; ಸಮಯ ಮುಗಿದಾಗ ಮಾತ್ರ ಪ್ರಶ್ನೆ ಸಲ್ಲಿಕೆಯಾಗುತ್ತದೆ. ಅಪೂರ್ಣ ಪ್ರಯತ್ನವನ್ನು ಕಾಪಾಡಲಾಗುವುದಿಲ್ಲ, ಆದ್ದರಿಂದ ಮತ್ತೆ ತೆರೆದಾಗ quiz ಆರಂಭದಿಂದ ಶುರುವಾಗಬಹುದು.</span></div></div>`;
    root().insertAdjacentHTML('beforeend',`<button class="quiz-button secondary" style="margin-top:10px" onclick="showQuizAdminLogin()">Admin Login</button>`);
  }
  window.showQuizSignup=function(){showMemberAuth('signup');};
  window.showQuizLogin=function(){showMemberAuth('login');};
  function showMemberAuth(mode='signup'){
    const signup=mode==='signup';root().innerHTML=`<div class="quiz-card"><div class="quiz-eyebrow">ಸದಸ್ಯರ ಪ್ರವೇಶ</div><h2 class="quiz-title">${signup?'ಹೊಸ ಖಾತೆ ರಚಿಸಿ':'Login'}</h2><p class="quiz-subtitle">ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಮತ್ತು ನಿಮ್ಮ password ಬಳಸಿ ಪ್ರವೇಶಿಸಿ.</p><form id="quizAuth">${signup?`<label class="quiz-field" for="quizName">ಪೂರ್ಣ ಹೆಸರು</label><input class="quiz-input" id="quizName" required maxlength="60" placeholder="ನಿಮ್ಮ ಹೆಸರು">`:''}<label class="quiz-field" for="quizMobile">ಮೊಬೈಲ್ ಸಂಖ್ಯೆ</label><input class="quiz-input" id="quizMobile" type="tel" inputmode="numeric" pattern="[0-9+() -]{8,18}" required placeholder="ಉದಾ: +91 98765 43210"><label class="quiz-field" for="quizPassword">Password</label><input class="quiz-input" id="quizPassword" type="password" minlength="8" required autocomplete="${signup?'new-password':'current-password'}" placeholder="ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು">${signup?`<label class="quiz-field" for="quizPasswordConfirm">Password ಮತ್ತೆ ನಮೂದಿಸಿ</label><input class="quiz-input" id="quizPasswordConfirm" type="password" minlength="8" required autocomplete="new-password">`:''}<p class="quiz-error" id="quizFormError"></p><button class="quiz-button" id="quizAuthSubmit">${signup?'Sign up':'Login'}</button></form><div style="display:grid;gap:9px;margin-top:12px">${signup?`<button class="quiz-button secondary" onclick="showQuizLogin()">Login</button>`:`<button class="quiz-button secondary" onclick="showQuizSignup()">Sign up</button><button class="quiz-button secondary" onclick="showQuizReset()">Password ಮರೆತಿರಾ?</button>`}<button class="quiz-button secondary" onclick="showQuizAdminLogin()"><i class="fa-solid fa-user-shield"></i> Admin Login</button><button class="quiz-button secondary" onclick="openQuiz()">ಹಿಂದೆ</button></div><p class="quiz-note">ಒಂದು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ ಒಂದು ಖಾತೆ. Password ಕನಿಷ್ಠ 8 ಅಕ್ಷರ ಇರಲಿ.</p></div>`;
    document.getElementById('quizAuth').onsubmit=async e=>{e.preventDefault();const error=document.getElementById('quizFormError'),button=document.getElementById('quizAuthSubmit'),mobile=document.getElementById('quizMobile').value.replace(/\D/g,'');button.disabled=true;error.textContent='';try{if(mobile.length<8)throw new Error('ಸರಿಯಾದ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.');const password=document.getElementById('quizPassword').value;if(signup&&password!==document.getElementById('quizPasswordConfirm').value)throw new Error('ಎರಡು password ಒಂದೇ ಆಗಿರಬೇಕು.');if(previewMode){member={id:'preview',name:signup?document.getElementById('quizName').value.trim():'Preview Member',mobile};localStorage.setItem(userKey,JSON.stringify(member));renderHome();return;}const data=await api({action:signup?'quizSignup':'quizLogin',name:signup?document.getElementById('quizName').value.trim():undefined,mobile,password});sessionStorage.setItem(userKey,JSON.stringify({token:data.token,member:data.member}));member=data.member;renderHome();}catch(err){error.textContent=err.message||'ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.';button.disabled=false;}};
  }
  window.showQuizReset=function(){root().innerHTML=`<div class="quiz-card"><div class="quiz-eyebrow">Password ಸಹಾಯ</div><h2 class="quiz-title">Password ಮರೆತಿರಾ?</h2><p class="quiz-subtitle">ಈಗ OTP ವ್ಯವಸ್ಥೆ ಸಕ್ರಿಯವಿಲ್ಲ. Admin ಅವರನ್ನು ಸಂಪರ್ಕಿಸಿ ತಾತ್ಕಾಲಿಕ password ಪಡೆಯಿರಿ. ಅದರ ಮೂಲಕ Login ಆದ ನಂತರ Profile‌ನಿಂದ ನಿಮ್ಮ password ಬದಲಾಯಿಸಿ.</p><button class="quiz-button" onclick="showQuizLogin()">Login‌ಗೆ ಹಿಂತಿರುಗಿ</button><button class="quiz-button secondary" style="margin-top:10px" onclick="openQuiz()">Quiz ಮುಖಪುಟ</button></div>`;};
  window.showQuizAdminLogin=function(){root().innerHTML=`<div class="quiz-card"><div class="quiz-eyebrow">Admin Portal</div><h2 class="quiz-title">Admin Login</h2><p class="quiz-subtitle">ಪ್ರಶ್ನೆಗಳು, ಸದಸ್ಯರ ಉತ್ತರಗಳು ಮತ್ತು ಅಂಕಗಳನ್ನು ನಿರ್ವಹಿಸಿ.</p><form id="quizAdminLoginForm"><label class="quiz-field">Admin password</label><input class="quiz-input" id="quizAdminPassword" type="password" required autocomplete="current-password"><p class="quiz-error" id="quizAdminError"></p><button class="quiz-button">Admin ಆಗಿ ಪ್ರವೇಶಿಸಿ</button></form><button class="quiz-button secondary" style="margin-top:10px" onclick="openQuiz()">ಹಿಂದೆ</button></div>`;document.getElementById('quizAdminLoginForm').onsubmit=async e=>{e.preventDefault();const error=document.getElementById('quizAdminError');try{const data=await api({action:'quizAdminLogin',password:document.getElementById('quizAdminPassword').value});sessionStorage.setItem('ayfaQuizAdminToken',data.token);if(data.mustChangePassword)showQuizAdminChangePassword();else showQuizAdminPanel();}catch(err){error.textContent=err.message;}};};
  window.showQuizAdminChangePassword=function(){root().innerHTML=`<div class="quiz-card"><div class="quiz-eyebrow">Admin • ಮೊದಲ login</div><h2 class="quiz-title">ತಾತ್ಕಾಲಿಕ password ಬದಲಿಸಿ</h2><p class="quiz-subtitle">Admin account ರಕ್ಷಿಸಲು ಹೊಸ password ಆಯ್ಕೆಮಾಡಿ.</p><form id="quizAdminChange"><label class="quiz-field">ಹೊಸ password</label><input class="quiz-input" id="adminNewPassword" type="password" minlength="10" required><label class="quiz-field">ಮತ್ತೆ ನಮೂದಿಸಿ</label><input class="quiz-input" id="adminConfirmPassword" type="password" minlength="10" required><p class="quiz-error" id="quizAdminError"></p><button class="quiz-button">Password ಉಳಿಸಿ</button></form></div>`;document.getElementById('quizAdminChange').onsubmit=async e=>{e.preventDefault();const password=document.getElementById('adminNewPassword').value;if(password!==document.getElementById('adminConfirmPassword').value){document.getElementById('quizAdminError').textContent='Password ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ.';return;}try{await api({action:'quizAdminChangePassword',token:sessionStorage.getItem('ayfaQuizAdminToken'),password});showQuizAdminPanel();}catch(err){document.getElementById('quizAdminError').textContent=err.message;}};};
  window.showQuizAdminPanel=async function(){root().innerHTML=`<div class="quiz-card"><div class="quiz-eyebrow">Admin Dashboard</div><h2 class="quiz-title">Quiz ನಿರ್ವಹಣೆ</h2><p class="quiz-subtitle">ಪ್ರಶ್ನೆಗಳನ್ನು ಸೇರಿಸಿ, ಸಲ್ಲಿಸಿದ ಉತ್ತರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ, ಅಂಕ ನಿಗದಿಪಡಿಸಿ.</p><div id="quizAdminContent"><p class="quiz-note">ದತ್ತಾಂಶ ಲೋಡ್ ಆಗುತ್ತಿದೆ…</p></div><button class="quiz-button secondary" style="margin-top:12px" onclick="showQuizAdminQuestionForm()">+ ಪ್ರಶ್ನೆ ಸೇರಿಸಿ</button><button class="quiz-button secondary" style="margin-top:10px" onclick="showQuizAdminReset()">ಸದಸ್ಯರ password reset</button><button class="quiz-button secondary" style="margin-top:10px" onclick="sessionStorage.removeItem('ayfaQuizAdminToken');openQuiz()">Logout</button></div>`;try{const data=await api({action:'quizAdminListAttempts',token:sessionStorage.getItem('ayfaQuizAdminToken')});const host=document.getElementById('quizAdminContent');if(!data.attempts.length){host.innerHTML='<p class="quiz-note">ಇನ್ನೂ ಯಾವುದೇ ಉತ್ತರಪತ್ರಿಕೆ ಸಲ್ಲಿಸಿಲ್ಲ.</p>';return;}host.innerHTML=data.attempts.map(a=>`<article class="quiz-admin-attempt"><h3>${safe(a.name)} <small>${safe(a.status)}</small></h3><p class="quiz-note">${safe(a.mobile)} • Auto score ${a.autoScore} • ${Math.floor(a.timeSeconds/60)}:${String(a.timeSeconds%60).padStart(2,'0')}</p>${a.answers.map(ans=>`<div class="quiz-admin-answer"><b>${ans.questionNo}. ${safe(ans.question)}</b><p>${safe(ans.answer.join(', ')||'ಉತ್ತರ ಇಲ್ಲ')}</p>${ans.type==='multiple'?`<label>ಅಂಕ: <input type="number" min="0" value="${ans.autoCorrect?(ans.adminPoints||1):0}" disabled></label>`:`<label>ಅಂಕ <input class="quiz-admin-points" type="number" min="0" step="0.5" value="${ans.adminPoints||0}" data-q="${ans.questionNo}"></label><input class="quiz-admin-note" placeholder="ಟಿಪ್ಪಣಿ (ಐಚ್ಛಿಕ)" data-q="${ans.questionNo}" value="${safe(ans.adminNote)}">`}</div>`).join('')}<button class="quiz-button" onclick="gradeQuizAttempt('${safe(a.attemptId)}')">ಅಂಕ ಉಳಿಸಿ ಮತ್ತು ಮೌಲ್ಯಮಾಪನ ಪೂರ್ಣಗೊಳಿಸಿ</button></article>`).join('');}catch(err){document.getElementById('quizAdminContent').innerHTML=`<p class="quiz-error">${safe(err.message)}</p>`;}};
  window.gradeQuizAttempt=async function(attemptId){const answers=[...root().querySelectorAll('.quiz-admin-points')].map(el=>({questionNo:Number(el.dataset.q),points:Number(el.value)||0,note:root().querySelector(`.quiz-admin-note[data-q="${el.dataset.q}"]`)?.value||''}));try{await api({action:'quizAdminGrade',token:sessionStorage.getItem('ayfaQuizAdminToken'),attemptId,answers});showQuizAdminPanel();}catch(err){alert(err.message);}};
  window.showQuizAdminQuestionForm=function(){root().innerHTML=`<div class="quiz-card"><div class="quiz-eyebrow">Admin • ಪ್ರಶ್ನೆ ನಿರ್ವಹಣೆ</div><h2 class="quiz-title">ಪ್ರಶ್ನೆ ಸೇರಿಸಿ</h2><form id="quizQuestionForm"><label class="quiz-field">Quiz ID</label><input class="quiz-input" name="quizId" value="current" required><label class="quiz-field">ಪ್ರಶ್ನೆ ಸಂಖ್ಯೆ (1–20)</label><input class="quiz-input" name="number" type="number" min="1" max="20" required><label class="quiz-field">ಪ್ರಶ್ನೆಯ ಪ್ರಕಾರ</label><select class="quiz-input" name="type"><option value="multiple">Multiple Answer</option><option value="typing">Typing Answer</option><option value="person">Guess the Person</option><option value="sound">Guess the Sound</option><option value="dance">Guess the Dance Video</option></select><label class="quiz-field">ಪ್ರಶ್ನೆ</label><textarea class="quiz-input" name="question" required rows="3"></textarea><label class="quiz-field">ಆಯ್ಕೆಗಳು (ಪ್ರತಿ ಸಾಲಿಗೆ ಒಂದು; Multiple Answer‌ಗೆ)</label><textarea class="quiz-input" name="options" rows="4"></textarea><label class="quiz-field">ಸರಿಯಾದ ಉತ್ತರ(ಗಳು), ಪ್ರತಿ ಸಾಲಿಗೆ ಒಂದು</label><textarea class="quiz-input" name="answers" required rows="3"></textarea><label class="quiz-field">ಸಮಯ (ಸೆಕೆಂಡ್)</label><input class="quiz-input" name="seconds" type="number" min="10" max="300" value="30"><label class="quiz-field">ಅಂಕ</label><input class="quiz-input" name="points" type="number" min="0" value="1"><label class="quiz-field">ಚಿತ್ರ/ಧ್ವನಿ/ವಿಡಿಯೋ URL (ಐಚ್ಛಿಕ)</label><input class="quiz-input" name="mediaURL" type="url"><p class="quiz-error" id="quizAdminError"></p><button class="quiz-button">ಪ್ರಶ್ನೆ ಉಳಿಸಿ</button></form><button class="quiz-button secondary" style="margin-top:10px" onclick="showQuizAdminPanel()">Admin Dashboard‌ಗೆ ಹಿಂದೆ</button></div>`;document.getElementById('quizQuestionForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),split=s=>String(s||'').split('\n').map(x=>x.trim()).filter(Boolean);try{await api({action:'quizAdminSaveQuestion',token:sessionStorage.getItem('ayfaQuizAdminToken'),question:{quizId:f.get('quizId'),number:Number(f.get('number')),type:f.get('type'),question:f.get('question'),options:split(f.get('options')),correctAnswers:split(f.get('answers')),seconds:Number(f.get('seconds')),points:Number(f.get('points')),mediaURL:f.get('mediaURL')}});showQuizAdminPanel();}catch(err){document.getElementById('quizAdminError').textContent=err.message;}};};
  window.showQuizAdminReset=function(){root().innerHTML=`<div class="quiz-card"><div class="quiz-eyebrow">Admin • Member ಸಹಾಯ</div><h2 class="quiz-title">Password reset ಮಾಡಿ</h2><p class="quiz-subtitle">ಸದಸ್ಯರ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ. ಹೊಸ ತಾತ್ಕಾಲಿಕ password ಅನ್ನು ಸದಸ್ಯರಿಗೆ ಖಾಸಗಿಯಾಗಿ ತಿಳಿಸಿ.</p><form id="adminMemberReset"><label class="quiz-field">ಸದಸ್ಯರ ಮೊಬೈಲ್</label><input class="quiz-input" id="adminResetMobile" required inputmode="tel"><p class="quiz-error" id="quizAdminError"></p><div id="adminResetResult"></div><button class="quiz-button">ತಾತ್ಕಾಲಿಕ password ರಚಿಸಿ</button></form><button class="quiz-button secondary" style="margin-top:10px" onclick="showQuizAdminPanel()">Admin Dashboard‌ಗೆ ಹಿಂದೆ</button></div>`;document.getElementById('adminMemberReset').onsubmit=async e=>{e.preventDefault();try{const data=await api({action:'quizAdminResetMemberPassword',token:sessionStorage.getItem('ayfaQuizAdminToken'),mobile:document.getElementById('adminResetMobile').value});document.getElementById('adminResetResult').innerHTML=`<p class="quiz-note">${safe(data.name)} ಅವರಿಗೆ ಈ ತಾತ್ಕಾಲಿಕ password ನೀಡಿ: <b>${safe(data.temporaryPassword)}</b>. ಅವರು login ಆದ ನಂತರ password ಬದಲಾಯಿಸಬೇಕು.</p>`;}catch(err){document.getElementById('quizAdminError').textContent=err.message;}};};
  window.showQuizChangePassword=function(){root().innerHTML=`<div class="quiz-card"><div class="quiz-eyebrow">Account ಸುರಕ್ಷತೆ</div><h2 class="quiz-title">Password ಬದಲಿಸಿ</h2><form id="memberChangePassword"><label class="quiz-field">ಪ್ರಸ್ತುತ password</label><input class="quiz-input" id="memberCurrentPassword" type="password" required><label class="quiz-field">ಹೊಸ password</label><input class="quiz-input" id="memberNewPassword" type="password" minlength="8" required><p class="quiz-error" id="quizFormError"></p><button class="quiz-button">Password ಉಳಿಸಿ</button></form><button class="quiz-button secondary" style="margin-top:10px" onclick="showQuizProfile()">ಹಿಂದೆ</button></div>`;document.getElementById('memberChangePassword').onsubmit=async e=>{e.preventDefault();try{await api({action:'quizChangePassword',token:savedAuth()?.token,currentPassword:document.getElementById('memberCurrentPassword').value,password:document.getElementById('memberNewPassword').value});root().innerHTML='<div class="quiz-card"><h2 class="quiz-title">Password ಬದಲಾಗಿದೆ</h2><button class="quiz-button" onclick="showQuizProfile()">ಪ್ರೊಫೈಲ್‌ಗೆ ಹಿಂತಿರುಗಿ</button></div>';}catch(err){document.getElementById('quizFormError').textContent=err.message;}};};
  window.beginQuiz=async function(){if(previewMode){questions=demoQuestions.map(q=>({...q}));startQuiz();return;}try{const response=await fetch(`${apiUrl}?action=quizQuestions&quizId=current`);const data=await response.json();if(!data.success||!data.questions?.length)throw new Error('ಈ quiz ಪ್ರಶ್ನೆಗಳು ಇನ್ನೂ ಪ್ರಕಟವಾಗಿಲ್ಲ. Admin ಮೊದಲು ಪ್ರಶ್ನೆಗಳನ್ನು ಸೇರಿಸಬೇಕು.');questions=data.questions.map(q=>({...q,text:q.question,time:q.seconds,answers:[],mediaURL:q.mediaURL}));startQuiz();}catch(err){root().innerHTML=`<div class="quiz-card"><h2 class="quiz-title">Quiz ಈಗ ಸಿದ್ಧವಾಗಿಲ್ಲ</h2><p class="quiz-note">${safe(err.message)}</p><button class="quiz-button secondary" onclick="openQuiz()">ಹಿಂದೆ</button></div>`;}};
  function startQuiz(){index=0;points=0;submittedAnswers=[];startedAt=Date.now();showQuestion();}
  function showQuestion(){clearInterval(ticker);questionLocked=false;selected=[];typed='';const q=questions[index];seconds=q.time;root().innerHTML=`<div class="quiz-card"><div class="quiz-timer-row"><span>ಪ್ರಶ್ನೆ ${index+1} / ${questions.length}</span><span class="quiz-timer" id="quizTimer"><i class="fa-regular fa-clock"></i> ${seconds} ಸೆಕೆಂಡ್</span></div><div class="quiz-progress"><span style="width:${index/questions.length*100}%"></span></div><span class="quiz-type">${typeNames[q.type]}</span><h2 class="quiz-question">${safe(q.text)}</h2>${renderMedia(q)}${q.type==='multiple'?`<div class="quiz-options">${q.options.map((o,i)=>`<label class="quiz-option"><input type="checkbox" value="${i}"> ${safe(o)}</label>`).join('')}</div>`:`<input class="quiz-input" id="quizAnswer" autocomplete="off" placeholder="ನಿಮ್ಮ ಉತ್ತರವನ್ನು ಟೈಪ್ ಮಾಡಿ">`}<p class="quiz-error" id="quizQuestionError"></p><button class="quiz-button" id="quizSubmit" style="margin-top:16px">ಉತ್ತರ ಸಲ್ಲಿಸಿ</button></div>`;
    root().querySelectorAll('.quiz-option').forEach(label=>label.onclick=()=>{setTimeout(()=>{const cb=label.querySelector('input');label.classList.toggle('selected',cb.checked);},0);});document.getElementById('quizSubmit').onclick=submitAnswer;ticker=setInterval(()=>{seconds--;const el=document.getElementById('quizTimer');if(el)el.innerHTML=`<i class="fa-regular fa-clock"></i> ${Math.max(0,seconds)} ಸೆಕೆಂಡ್`;if(seconds<=0)submitAnswer(true);},1000);
  }
  function submitAnswer(timedOut=false){if(questionLocked)return;questionLocked=true;clearInterval(ticker);const q=questions[index];let given=[];if(q.type==='multiple')given=[...root().querySelectorAll('.quiz-option input:checked')].map(el=>q.options[Number(el.value)]);else given=[(document.getElementById('quizAnswer')?.value||'').trim()];submittedAnswers.push(given);if(previewMode){const normalize=s=>String(s).trim().toLocaleLowerCase('kn').replace(/[.,!?\s]+/g,'');const correct=q.answers.every(a=>given.some(g=>normalize(g)===normalize(a)))&&given.every(g=>q.answers.some(a=>normalize(a)===normalize(g)));if(correct)points++;}if(index<questions.length-1){index++;showQuestion();}else finishQuiz();}
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&ticker)clearInterval(ticker);else if(document.visibilityState==='visible'&&ticker&&questions.length&&index<questions.length){ticker=setInterval(()=>{seconds--;const el=document.getElementById('quizTimer');if(el)el.innerHTML=`<i class="fa-regular fa-clock"></i> ${Math.max(0,seconds)} ಸೆಕೆಂಡ್`;if(seconds<=0)submitAnswer(true);},1000);}});
  async function finishQuiz(){clearInterval(ticker);const elapsed=Math.round((Date.now()-startedAt)/1000);if(!previewMode){root().innerHTML='<div class="quiz-card"><h2 class="quiz-title">ಉತ್ತರಗಳನ್ನು ಉಳಿಸುತ್ತಿದ್ದೇವೆ…</h2></div>';try{const auth=savedAuth();const data=await api({action:'quizSubmit',token:auth?.token,quizId:String(questions[0]?.quizId||'current'),startedAt,answers:submittedAnswers});root().innerHTML=`<div class="quiz-card"><div class="quiz-eyebrow"><i class="fa-solid fa-circle-check"></i> ಉತ್ತರಗಳು ಸಲ್ಲಿಕೆಯಾಗಿವೆ</div><h1 class="quiz-title" style="text-align:center">ಧನ್ಯವಾದಗಳು, ${safe(member.name.split(' ')[0])}!</h1><p class="quiz-result-meta">${safe(data.status)}. ನಿಮ್ಮ ಫಲಿತಾಂಶ ಮೌಲ್ಯಮಾಪನದ ನಂತರ ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.</p><button class="quiz-button" onclick="showQuizProfile()">ನನ್ನ ಫಲಿತಾಂಶ</button><button class="quiz-button secondary" style="margin-top:10px" onclick="openQuiz()">Quiz ಮುಖಪುಟ</button></div>`;}catch(err){root().innerHTML=`<div class="quiz-card"><h2 class="quiz-title">ಉತ್ತರ ಸಲ್ಲಿಕೆಯಾಗಲಿಲ್ಲ</h2><p class="quiz-error">${safe(err.message)}</p><button class="quiz-button" onclick="openQuiz()">Quiz ಮುಖಪುಟ</button></div>`;}return;}const result={name:member.name,score:points,total:questions.length,elapsed,at:new Date().toISOString()};const all=JSON.parse(localStorage.getItem(resultKey)||'[]');all.unshift(result);localStorage.setItem(resultKey,JSON.stringify(all.slice(0,100)));const rank=all.filter(x=>x.score>points||(x.score===points&&x.elapsed<elapsed)).length+1;root().innerHTML=`<div class="quiz-card"><div class="quiz-eyebrow"><i class="fa-solid fa-circle-check"></i> ಕ್ವಿಜ್ ಪೂರ್ಣಗೊಂಡಿದೆ</div><h1 class="quiz-title" style="text-align:center">ಚೆನ್ನಾಗಿ ಆಡಿದಿರಿ, ${safe(member.name.split(' ')[0])}!</h1><div class="quiz-result-score">${points} <small style="font-size:20px;color:#81918a">/ ${questions.length}</small></div><p class="quiz-result-meta">ಸರಿಯಾದ ಉತ್ತರಗಳು ${points} • ಸಮಯ ${Math.floor(elapsed/60)} ನಿಮಿಷ ${elapsed%60} ಸೆಕೆಂಡ್</p><div class="quiz-stats"><div class="quiz-stat"><b>${Math.round(points/questions.length*100)}%</b><span>ಅಂಕ</span></div><div class="quiz-stat"><b>#${rank}</b><span>ಈ preview ಸಾಧನದ ಸ್ಥಾನ</span></div><div class="quiz-stat"><b>${all.length}</b><span>ಪ್ರಯತ್ನಗಳು</span></div></div><button class="quiz-button" onclick="showQuizProfile()">ಅಂಕಪಟ್ಟಿ ನೋಡಿ</button><button class="quiz-button secondary" style="margin-top:10px" onclick="openQuiz()">Quiz ಮುಖಪುಟಕ್ಕೆ</button></div>`;}
  window.showQuizProfile=async function(){let rows=[];if(previewMode)rows=JSON.parse(localStorage.getItem(resultKey)||'[]');else{try{const data=await api({action:'quizMyResults',token:savedAuth()?.token});rows=data.results||[];}catch(err){root().innerHTML=`<div class="quiz-card"><p class="quiz-error">${safe(err.message)}</p><button class="quiz-button" onclick="openQuiz()">ಹಿಂದೆ</button></div>`;return;}}const last=rows[0],scoreRows=rows.filter(r=>r.score!=null);root().innerHTML=`<div class="quiz-card"><div class="quiz-eyebrow">ನಿಮ್ಮ ವಿವರ</div><h2 class="quiz-title">ನಮಸ್ಕಾರ, ${safe(member?.name||'ಸದಸ್ಯರೇ')}</h2><p class="quiz-subtitle">${safe(member?.mobile||'')}</p><div class="quiz-stats"><div class="quiz-stat"><b>${last?.score==null?'—':last.score+'/'+last.totalQuestions}</b><span>ಕೊನೆಯ ಅಂಕ</span></div><div class="quiz-stat"><b>${rows.length}</b><span>ಭಾಗವಹಿಸಿದ quiz</span></div><div class="quiz-stat"><b>${scoreRows.reduce((n,r)=>n+(r.score||0),0)}</b><span>ಒಟ್ಟು ಅಂಕ</span></div></div><h3>ನಿಮ್ಮ ಪ್ರಯತ್ನಗಳು</h3>${rows.length?`<table class="quiz-leaderboard">${rows.map((r,i)=>`<tr><td>${i+1}. ${r.date?new Date(r.date).toLocaleDateString('kn-IN'):'Quiz'} · ${safe(r.status)}</td><td>${r.score==null?'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ':`${r.score} / ${r.totalQuestions}`}</td></tr>`).join('')}</table>`:'<p class="quiz-note">ಇನ್ನೂ quiz ಪ್ರಯತ್ನಿಸಿಲ್ಲ.</p>'}<button class="quiz-button" style="margin-top:18px" onclick="renderQuizHome()">ಹಿಂದೆ</button></div>`;};window.renderQuizHome=renderHome;
})();
